### ISSUE TITLE
Gate signal reads > 100

### ISSUE THREAD

**Issue by michaelotto** [iavorvel/MyLD2410#4]
Hi, another peculiar bug for me: The stationary gate signals for gate 7 and 8 are odd, gate 7 often returns a value > 100 and gate 8 is almost always 1. This is after a factory reset of the sensor:

So this is a stationary reading: [ 100 100 71 45 28 28 22 106 1 ]

**Comment by iavorvel** [comment]
Hi Michael,

Unfortunately, the behavior you observed is probably caused by damage to the sensor. 

I have the same issue with my first LD2410C sensor. Its stationary signals are: [54 43 19 8 8 6 3 **118 1** ]. I believe too strong reflection may damage the amplifiers for particular gates. Since then I have been very careful not to touch my new sensors with fingers while in operation. 

Another possible cause is a firmware bug that when triggered, persists even after factory reset.

**Comment by michaelotto** [comment]
Hi Iavor, that may very well be the case, I did touch the sensor, I didn't know it was sensitive to that. Thanks for the info. Gates 7 and 8 are really just reporting nonsense in my case now. But I'll have to order a few more sensors anyway.

**Comment by michaelotto** [comment]
It looks like it is working now, thank you very much! Maybe the sensor is not broken after all.

**Comment by iavorvel** [comment]
Yes, I realized that after testing with my new sensors. 
I added a new function: getLightLevel(), which might be useful too

**Comment by michaelotto** [comment]
One strange thing though, the first two gates of the stationary always report 0 now. Moving gates seem fine.

**Comment by iavorvel** [comment]
They are supposed to be zero, that's why they don't let the user configure them. If you have the mobile app, it reports zero  for gates 0 and 1 too.

**Comment by michaelotto** [comment]
I don't mean the thresholds, though, I mean the signals!

**Comment by iavorvel** [comment]
Yes, the signals too.
